name: Test LaTeX Compilation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-compile:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        folder:
          - resume
          - quick-note
          - presentation

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: ${{ matrix.folder }}.tex
          working_directory: ${{ matrix.folder }}

      - name: Copy PDF to output directory
        run: cp ${{ matrix.folder }}/${{ matrix.folder }}.pdf output/

      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.folder }}-pdf
          path: output/${{ matrix.folder }}.pdf
