name: Test LaTeX Compilation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-compile:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        folder:
          - resume
          - quick-note
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: ${{ matrix.folder }}.tex
          working_directory: ${{ matrix.folder }}
